IS_KEYBOARD = 0
IS_MOUSE = 1

KEY_DOWN = 0x00
KEY_UP = 0x01
KEY_E0 = 0x02
KEY_E1 = 0x04
KEY_TERMSRV_SET_LED = 0x08
KEY_TERMSRV_SHADOW = 0x10
KEY_TERMSRV_VKPACKET = 0x20

FILTER_KEY_NONE = 0x0000
FILTER_KEY_ALL = 0xFFFF
FILTER_KEY_DOWN = KEY_UP,
FILTER_KEY_UP = KEY_UP << 1
FILTER_KEY_E0 = KEY_E0 << 1
FILTER_KEY_E1 = KEY_E1 << 1
FILTER_KEY_TERMSRV_SET_LED = KEY_TERMSRV_SET_LED << 1
FILTER_KEY_TERMSRV_SHADOW = KEY_TERMSRV_SHADOW << 1
FILTER_KEY_TERMSRV_VKPACKET = KEY_TERMSRV_VKPACKET << 1
